---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-clh
handler: kata-clh
overhead:
    podFixed:
        memory: "130Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-cloud-hypervisor
handler: kata-cloud-hypervisor
overhead:
    podFixed:
        memory: "130Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-dragonball
handler: kata-dragonball
overhead:
    podFixed:
        memory: "130Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-fc
handler: kata-fc
overhead:
    podFixed:
        memory: "130Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-nvidia-gpu
handler: kata-qemu-nvidia-gpu
overhead:
    podFixed:
        memory: "160Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-nvidia-gpu-256g
handler: kata-qemu-nvidia-gpu-256g
overhead:
    podFixed:
        memory: "256Gi"
        cpu: "16.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-nvidia-gpu-512g
handler: kata-qemu-nvidia-gpu-512g
overhead:
    podFixed:
        memory: "512Gi"
        cpu: "32.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-nvidia-gpu-708g
handler: kata-qemu-nvidia-gpu-708g
overhead:
    podFixed:
        memory: "708Gi"
        cpu: "64.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-se
handler: kata-qemu-se
overhead:
    podFixed:
        memory: "2048Mi"
        cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-sev
handler: kata-qemu-sev
overhead:
    podFixed:
        memory: "2048Mi"
        cpu: "1.0"
scheduling:
    nodeSelector:
        katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-snp
handler: kata-qemu-snp
overhead:
    podFixed:
        memory: "2048Mi"
        cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-tdx
handler: kata-qemu-tdx
overhead:
    podFixed:
        memory: "2048Mi"
        cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu
handler: kata-qemu
overhead:
    podFixed:
        memory: "160Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-remote
handler: kata-remote
overhead:
    podFixed:
        memory: "120Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-stratovirt
handler: kata-stratovirt
overhead:
    podFixed:
        memory: "130Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
